twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/dsfr.html.twig']
    globals:
        app_env: '%env(APP_ENV)%'
        app_name: 'Au bon transit...' 
        app_tagline: 'COMGENDGP'
        app_slug: 'Gestion logistique'

when@test:
    twig:
        strict_variables: true
